TCOI5/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('controle_financeiro/', include('controle_financeiro.urls'))
]

controle_financeiro/models/grupoModel.py
from django.db import models
from .permissaoModel import PermissaoModel

class GrupoModel(models.Model):
    grupo_id = models.AutoField(primary_key=True)
    grupo_nome = models.CharField(max_length=45, null=False, verbose_name="Nome")
    grupo_permissao = models.ForeignKey(PermissaoModel, null=True, on_delete=models.CASCADE)

    class Meta:
        ordering = ['grupo_nome']
        verbose_name = 'Grupo'
        verbose_name_plural = 'Grupos'

    def __str__(self):
        return self.grupo_nome

controle_financeiro/models/permissaoModel.py
from django.db import models

class PermissaoModel(models.Model):
    permissao_id = models.AutoField(primary_key=True)
    permissao_nome = models.CharField(max_length=45, null=False, verbose_name="Nome")
    permissao_read = models.BooleanField(verbose_name="Permissao de leitura")
    permissao_write = models.BooleanField(verbose_name="Permissao de escrita")
    permissao_delete = models.BooleanField(verbose_name="Permissao de exclusão")

    class Meta:
        ordering = ['permissao_nome']
        verbose_name = 'Permissão'
        verbose_name_plural = 'Permissões'

    def __str__(self):
        return self.permissao_nome

controle_financeiro/models/planoContasModel.py
from django.db import models

class PlanoContasModel(models.Model):
    plano_contas_id = models.AutoField(primary_key=True)
    plano_contas_referencial = models.CharField(max_length=45, null=False, verbose_name="Referencial")
    plano_contas_descricao = models.CharField(max_length=45, null=False, verbose_name="Descricao")
    plano_contas_inicio_validade = models.DateField(null=True, blank=False, verbose_name="Inicio Validade")
    plano_contas_fim_validade = models.DateField(null=True, blank=False, verbose_name="Fim Validade")
    plano_contas_tipo = models.CharField(max_length=1, null=False, verbose_name="Tipo")

    class Meta:
        ordering = ['plano_contas_descricao']
        verbose_name = 'PlanoConta'
        verbose_name_plural = 'PlanosContas'

    def __str__(self):
        return self.plano_contas_descricao

controle_financeiro/models/usuarioGrupoModel.py
from django.db import models
from .grupoModel import GrupoModel
from .usuarioModel import UsuarioModel
from datetime import datetime

class UsuarioGrupoModel(models.Model):
    usuario = models.ForeignKey(UsuarioModel, on_delete=models.CASCADE)
    grupo = models.ForeignKey(GrupoModel, on_delete=models.CASCADE)
    data_cadastro = models.DateField(null=False, verbose_name='Data de Cadastro', default=datetime.now)
    data_entrada = models.DateField(verbose_name='Data de entrada', null=True)
    data_saida = models.DateField(verbose_name='Data de Saida', null=True)

    class Meta:
        ordering = ['data_cadastro']
        verbose_name = 'UsuarioGrupo'
        verbose_name_plural = 'UsuariosGrupos'
        unique_together = (("usuario","grupo"))

    def __str__(self):
        return self.usuario.usuario_nome + self.grupo.grupo_nome

controle_financeiro/models/usuarioModel.py
from django.db import models

class UsuarioModel(models.Model):
    usuario_id  = models.AutoField(primary_key=True)
    usuario_nome = models.CharField(max_length=45,null=False,blank=False,verbose_name="Nome")
    usuario_email = models.CharField(max_length=45,null=False,blank=False,verbose_name="Email")
    usuario_senha = models.CharField(max_length=45,null=False,blank=False,verbose_name="Senha")

    class Meta:
        ordering = ['usuario_nome']
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.usuario_nome

controle_financeiro/forms/grupoForm.py
from django import forms
from ..models import GrupoModel, PermissaoModel

class GrupoForm(forms.ModelForm):
    grupo_nome = forms.CharField(required=True, label="Nome")
    grupo_permissao = forms.ModelChoiceField(queryset=PermissaoModel.objects.all(), label='permissão')

    class Meta:
        model = GrupoModel
        fields = [
            'grupo_nome'
        ]

controle_financeiro/forms/permissaoForm.py
from django import forms
from ..models import PermissaoModel

class PermissaoForm(forms.ModelForm):
    permissao_nome = forms.CharField(required=True, label="Nome")
    permissao_read = forms.BooleanField(label="leitura", required=False, widget=forms.CheckboxInput())
    permissao_write = forms.BooleanField(label="escrita", required=False, widget=forms.CheckboxInput())
    permissao_delete = forms.BooleanField(label="remoção", required=False, widget=forms.CheckboxInput())

    class Meta:
        model = PermissaoModel
        fields = [
            'permissao_nome',
            'permissao_read',
            'permissao_write',
            'permissao_delete'
        ]

controle_financeiro/forms/planoContasForm.py
from django import forms
from ..models import PlanoContasModel

class PlanoContasForm(forms.ModelForm):
    plano_contas_referencial = forms.CharField(max_length=45, label="Referencial")
    plano_contas_descricao = forms.CharField(max_length=45, label="Descricao")
    plano_contas_inicio_validade = forms.DateField(label="Inicio Validade", widget=forms.DateTimeInput())
    plano_contas_fim_validade = forms.DateField(label="Fim Validade", widget=forms.DateTimeInput())
    plano_contas_tipo = forms.CharField(max_length=1, label="Tipo")

    class Meta:
        model = PlanoContasModel
        fields = [
            'plano_contas_referencial',
            'plano_contas_descricao',
            'plano_contas_inicio_validade',
            'plano_contas_fim_validade',
            'plano_contas_tipo'
        ]

    def __init__(self, *args, **kwargs):
        super(PlanoContasForm, self).__init__(*args, **kwargs)
        locale_date_format = '%d/%m/%Y'
        self.fields['plano_contas_inicio_validade'].input_formats = [locale_date_format, ]
        self.fields['plano_contas_inicio_validade'].widget = forms.DateInput(format=locale_date_format,
                                                                             attrs={'class': 'form-control js-date'})
        self.fields['plano_contas_fim_validade'].input_formats = [locale_date_format, ]
        self.fields['plano_contas_fim_validade'].widget = forms.DateInput(format=locale_date_format,
                                                                          attrs={'class': 'form-control js-date'})

controle_financeiro/forms/usuarioForm.py
from django import forms
from ..models import UsuarioModel

class UsuarioForm(forms.ModelForm):
    usuario_nome = forms.CharField(required=True, label="Nome")
    usuario_email = forms.EmailField(required=True, label="Email", widget=forms.EmailInput())
    usuario_senha = forms.CharField(required=True, label="Senha",widget=forms.PasswordInput())

    class Meta:
        model = UsuarioModel
        fields = [
            'usuario_nome',
            'usuario_email'
        ]

controle_financeiro/forms/usuarioGrupoForm.py
from  django import forms
from ..models import UsuarioGrupoModel, UsuarioModel, GrupoModel

class UsuarioGrupoForm(forms.ModelForm):
    grupo = forms.ModelChoiceField(queryset=GrupoModel.objects.all(), label='grupo')
    usuario = forms.ModelChoiceField(queryset=UsuarioModel.objects.all(), label='usuario')
    data_cadastro = forms.DateField(required=False, label="Data de cadastro", widget=forms.DateInput(), input_formats='%d-%m-%y')

    class Meta:
        model = UsuarioGrupoModel
        fields = [
            'grupo',
            'usuario',
            'data_cadastro'
        ]

controle_financeiro/views/grupoView.py
from django.shortcuts import render, redirect, get_object_or_404
from ..forms import GrupoForm
from ..models import GrupoModel

def listar(request):
    form = GrupoModel.objects.all()
    context = {
        'form':form
    }
    return render(request, 'grupo/listar.html', context)

def inserir(request):
    form = GrupoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('listar_grupo')
    context = {
        'form':form
    }
    return render(request, 'grupo/novo.html', context)

def alterar(request,id):
    grupo = get_object_or_404(GrupoModel, grupo_id=id)
    form = GrupoForm(request.POST or None, instance=grupo)
    if form.is_valid():
        form.save()
        return redirect('listar_grupo')
    context = {
        'form':form
    }
    return render(request, 'grupo/novo.html', context)

def remover(request,id):
    grupo = get_object_or_404(GrupoModel, grupo_id = id)
    form = GrupoForm(request.POST or None, instance=grupo)
    if request.method == 'POST':
        grupo.delete()
        return redirect('listar_grupo')
    context={
        'form':form
    }
    return render(request, 'grupo/novo.html', context)

def exibir(request, id):
    grupo = get_object_or_404(GrupoModel, grupo_id=id)
    form = GrupoForm(request.POST or None, instance=grupo)
    if request.method == 'POST':
        return redirect('listar_grupo')
    context={
        'form':form
    }
    return render(request, 'grupo/novo.html', context)

controle_financeiro/views/permissaoView.py
from django.shortcuts import render, redirect, get_object_or_404
from ..forms import PermissaoForm
from ..models import PermissaoModel

def listar(request):
    form = PermissaoModel.objects.all()
    context = {
        'form':form
    }
    return render(request, 'permissao/listar.html', context)

def inserir(request):
    form = PermissaoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('listar_permissao')
    context = {
        'form':form
    }
    return render(request, 'permissao/novo.html', context)

def alterar(request,id):
    grupo = get_object_or_404(PermissaoModel, grupo_id=id)
    form = PermissaoForm(request.POST or None, instance=grupo)
    if form.is_valid():
        form.save()
        return redirect('listar_permissao')
    context = {
        'form':form
    }
    return render(request, 'permissao/novo.html', context)

def remover(request,id):
    grupo = get_object_or_404(PermissaoModel, grupo_id = id)
    form = PermissaoForm(request.POST or None, instance=grupo)
    if request.method == 'POST':
        grupo.delete()
        return redirect('listar_permissao')
    context={
        'form':form
    }
    return render(request, 'permissao/novo.html', context)

def exibir(request, id):
    grupo = get_object_or_404(PermissaoModel, grupo_id=id)
    form = PermissaoForm(request.POST or None, instance=grupo)
    if request.method == 'POST':
        return redirect('listar_permissao')
    context={
        'form':form
    }
    return render(request, 'permissao/novo.html', context)

controle_financeiro/views/planoContasView.py
from django.shortcuts import render, redirect, get_object_or_404
from ..forms import PlanoContasForm
from ..models import PlanoContasModel

def listar(request):
    form = PlanoContasModel.objects.all()
    context = {
        'form':form
    }
    return render(request, 'planoContas/listar.html', context)

def inserir(request):
    form = PlanoContasForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('listar_plano_conta')
    context = {
        'form':form
    }
    return render(request, 'planoContas/novo.html', context)

def alterar(request,id):
    grupo = get_object_or_404(PlanoContasModel, grupo_id=id)
    form = PlanoContasForm(request.POST or None, instance=grupo)
    if form.is_valid():
        form.save()
        return redirect('listar_plano_conta')
    context = {
        'form':form
    }
    return render(request, 'planoContas/novo.html', context)

def remover(request,id):
    grupo = get_object_or_404(PlanoContasModel, grupo_id = id)
    form = PlanoContasForm(request.POST or None, instance=grupo)
    if request.method == 'POST':
        grupo.delete()
        return redirect('listar_plano_conta')
    context={
        'form':form
    }
    return render(request, 'planoContas/novo.html', context)

def exibir(request, id):
    grupo = get_object_or_404(PlanoContasModel, grupo_id=id)
    form = PlanoContasForm(request.POST or None, instance=grupo)
    if request.method == 'POST':
        return redirect('listar_plano_conta')
    context={
        'form':form
    }
    return render(request, 'planoContas/novo.html', context)

controle_financeiro/views/usuarioGrupoView.py
from django.shortcuts import render, redirect, get_object_or_404
from ..forms import UsuarioGrupoForm
from ..models import UsuarioGrupoModel, UsuarioModel, GrupoModel

def listar(request):
    form = UsuarioGrupoModel.objects.all()
    context = {
        'form':form
    }
    return render(request, 'usuarioGrupo/listar.html', context)

def inserir(request):
    form = UsuarioGrupoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('listar_usuario_grupo')
    context = {
        'form':form
    }
    return render(request, 'usuarioGrupo/novo.html', context)


def remover(request, idUsuario, idGrupo):
    usuario = get_object_or_404(UsuarioModel, usuario_id=idUsuario)
    grupo = get_object_or_404(GrupoModel, grupo_id=idGrupo)
    usuarioGrupo = get_object_or_404(UsuarioGrupoModel, usuario=usuario, grupo=grupo)
    form = UsuarioGrupoForm(request.POST or None, instance=usuarioGrupo)
    if request.method == 'POST':
        grupo.delete()
        return redirect('listar_usuario_grupo')
    context={
        'form':form
    }
    return render(request, 'usuarioGrupo/novo.html', context)

controle_financeiro/views/usuarioView.py
from django.shortcuts import render, redirect, get_object_or_404
from ..forms import UsuarioForm
from ..models import UsuarioModel


def listar(request):
    form = UsuarioModel.objects.all()
    context = {
        'form':form
    }
    return render(request, 'usuario/listar.html', context)

def inserir(request):
    form = UsuarioForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('listar_usuario')
    context = {
        'form': form
    }
    return render(request, 'usuario/novo.html', context)

def alterar(request, id):
    usuario = get_object_or_404(UsuarioModel, usuario_id=id)
    form = UsuarioForm(request.POST or None, instance=usuario)
    if form.is_valid():
        form.save()
        return redirect('listar_usuario')
    context = {
        'form': form,
    }
    return render(request, 'usuario/novo.html', context)

def remover(request, id):
    usuario = get_object_or_404(UsuarioModel, pessoa_id=id)
    form = UsuarioForm(request.POST or None, instance = usuario)
    if request.method == 'POST':
        usuario.delete()
        return redirect('listar_usuario')
    context={
        'form':form,
    }
    return render(request, 'usuario/novo.html', context)


def exibir(request, id):
    pessoa = get_object_or_404(UsuarioModel, pessoa_id=id)
    form = UsuarioForm(request.POST or None, instance = pessoa)
    if request.method == 'POST':
        return redirect('listar_usuario')
    context={
        'form':form,
    }
    return render(request, 'usuario/novo.html', context)

controle_financeiro/templates/planoContas/listar.html
{% extends "base.html" %}

{% load widget_tweaks %}

{%block main%}
<div class="container-fluid">
    <div class="table-responsive">
        <table class="table
                      table-striped
                      table-bordered
                      table-hover
                      table-collapse">
         <thead>
            <tr>
                <th>Referencial</th>
                <th>Descrição</th>
                <th>Inicio Validade</th>
                <th>Fim Validade</th>
                <th>Tipo</th>
                <th>Ações</th>
            </tr>
         </thead>
         <tbody>
            {%for u in form%}
            <tr>
                <td>{{ u.plano_contas_referencial }}</td>
                <td>{{ u.plano_contas_descricao }}</td>
                <td>{{ u.plano_contas_inicio_validade }}</td>
                <td>{{ u.plano_contas_fim_validade }}</td>
                <td>{{ u.plano_contas_tipo }}</td>
				<td class="text-center">
				  <a id="idAlterar" class="btn btn-warning btn-sm"
				     title="Alterar dados do grupo"
					 href="{% url 'alterar_plano_conta' u.plano_contas_id%}">
                     <i class="fa fa-pencil-square" aria-hidden="true"></i>
            	  </a>
				  <a id="idExcluir" class="btn btn-danger btn-sm"
				     title="Excluir dados do grupo"
					 href="{% url 'remover_plano_conta' u.plano_contas_id%}">
                     <i class="fa fa-trash-o" aria-hidden="true"></i>
				  </a>
                  <a id="idConsultar" class="btn btn-info btn-sm"
				     title="Consultar dados do grupo"
					 href="{% url 'exibir_plano_conta' u.plano_contas_id%}">
                     <i class="fa fa-eye" aria-hidden="true"></i>
				  </a>
				</td>
            </tr>
            {%endfor%}
         </tbody>
        </table>
        <a id="idIncluir" class="btn btn-primary" href="{% url 'inserir_plano_conta' %}">Nova Permissão <i class="fa fa-check-square-o" aria-hidden="true"></i></a>


    </div>


</div>

{%endblock%}

controle_financeiro/templates/planoContas/novo.html
{% extends "base.html" %}

{% load widget_tweaks %}

{%block main%}

<form class="form-horizontal" role="form" method="post" >
       {%csrf_token%}
  
       <div class="row">

            <div class="col-sm-8 offset-2">
	          <div class="form-group {% if field.errors %} has-error {%endif%}">
	          <label for="id_plano_contas_referencial"
	                 class="col-sm-2 control-label">{{form.plano_contas_referencial.label}}</label>
	                 {% render_field form.plano_contas_referencial class='form-control'%}
	                 {% for error in form.plano_contas_referencial.errors %}
	                    <span class="help-block">{{error}}</span>
	                 {% endfor %}
	          </div>
	       </div>

	       <div class="col-sm-8 offset-2">
	          <div class="form-group {% if field.errors %} has-error {%endif%}">
	          <label for="id_plano_contas_descricao"
	                 class="col-sm-2 control-label">{{form.plano_contas_descricao.label}}</label>
	                 {% render_field form.plano_contas_descricao class='form-control'%}
	                 {% for error in form.plano_contas_descricao.errors %}
	                    <span class="help-block">{{error}}</span>
	                 {% endfor %} 
	          </div>
	       </div>
             <div class="col-sm-8 offset-2">
	          <div class="form-group {% if field.errors %} has-error {%endif%}">
	          <label for="id_plano_contas_inicio_validade"
	                 class="col-sm-2 control-label">{{form.plano_contas_inicio_validade.label}}</label>
	                 {% render_field form.plano_contas_inicio_validade class='form-control js-date'%}
	                 {% for error in form.plano_contas_inicio_validade.errors %}
	                    <span class="help-block">{{error}}</span>
	                 {% endfor %}
	          </div>
	       </div>

           <div class="col-sm-8 offset-2">
	          <div class="form-group {% if field.errors %} has-error {%endif%}">
	          <label for="id_plano_contas_fim_validade"
	                 class="col-sm-2 control-label">{{form.plano_contas_fim_validade.label}}</label>
	                 {% render_field form.plano_contas_fim_validade class='form-control js-date'%}
	                 {% for error in form.plano_contas_fim_validade.errors %}
	                    <span class="help-block">{{error}}</span>
	                 {% endfor %}
	          </div>
	       </div>

            <div class="col-sm-8 offset-2">
	          <div class="form-group {% if field.errors %} has-error {%endif%}">
	          <label for="id_plano_contas_tipo"
	                 class="col-sm-2 control-label">{{form.plano_contas_tipo.label}}</label>
	                 {% render_field form.plano_contas_tipo class='form-control'%}
	                 {% for error in form.plano_contas_tipo.errors %}
	                    <span class="help-block">{{error}}</span>
	                 {% endfor %}
	          </div>
	        </div>

           <div class="offset-2 col-sm-2">
	              <button type="submit"
	                      class="btn btn-primary">Salvar</button>
          </div>
       </div> 

  </form>

<script>
  $(function () {
    $("#datetimepickerInicioValidade").datetimepicker({
      format: 'DD/MM/YYYY'
    });
    $("#datetimepickerFimValidade").datetimepicker({
      format: 'DD/MM/YYYY'
    });
  });
</script>
{%endblock%}